export type CalibrationTag =
  | 'active_lifestyle'
  | 'creative_arts'
  | 'intellectual_curiosity'
  | 'social_energy'
  | 'homebody_rhythm'
  | 'outdoor_energy'
  | 'mindful_service'
  | 'adventure'
  // Physical-trait appearance tags (replaced abstract style/vibe tags — Option B).
  // Hair color
  | 'blonde'
  | 'dark_hair'
  | 'red_hair'
  | 'light_brown_hair'
  // Skin tone
  | 'light_skin'
  | 'medium_skin'
  | 'dark_skin'
  // Build
  | 'slim_build'
  | 'athletic_build'
  | 'curvy_build'
  | 'full_build'
  | 'tall'
  | 'short'
  // Style
  | 'clean_cut'
  | 'edgy_look';

export type InterestCalibrationCard = {
  id: string;
  icon: string;
  label: string;
  description: string;
  tags: CalibrationTag[];
};

export type LookCalibrationCard = {
  id: string;
  photoUrl: string;
  name: string;
  age: number;
  tags: CalibrationTag[];
};

/**
 * Generates a self-labeling look-card placeholder as a PNG URL that React
 * Native's <Image> can render without SVG dependencies.
 */
export function makeLabeledLookPhoto(tags: CalibrationTag[]): string {
  const label = encodeURIComponent(tags.join(' · '));
  return `https://placehold.co/600x600.png?text=${label}`;
}

// "Scale profiles" calibration library: each card has explicit tags that map
// to preference-vector axes.
export const INTEREST_CALIBRATION_DECK: InterestCalibrationCard[] = [
  { id: 'int_01', icon: '🏃', label: 'Marathon running', description: 'Trains 4x a week, recently ran NYC', tags: ['active_lifestyle', 'adventure'] },
  { id: 'int_02', icon: '🏺', label: 'Pottery & ceramics', description: 'Wheel-throwing on weekends', tags: ['creative_arts', 'homebody_rhythm'] },
  { id: 'int_03', icon: '📚', label: 'Literary fiction', description: 'Reads everything by Sally Rooney and Murakami', tags: ['intellectual_curiosity', 'homebody_rhythm'] },
  { id: 'int_04', icon: '🎷', label: 'Live jazz nights', description: 'Knows the city\'s underground venues', tags: ['social_energy', 'creative_arts'] },
  { id: 'int_05', icon: '🥾', label: 'Weekend hiking', description: 'Has a goal to summit one new peak a month', tags: ['outdoor_energy', 'adventure'] },
  { id: 'int_06', icon: '🍳', label: 'Cooking from scratch', description: 'Bakes sourdough every Sunday', tags: ['homebody_rhythm', 'creative_arts'] },
  { id: 'int_07', icon: '🎲', label: 'Board game nights', description: 'Hosts strategy night every other Friday', tags: ['social_energy', 'intellectual_curiosity'] },
  { id: 'int_08', icon: '💃', label: 'Salsa dancing', description: 'Started taking lessons six months ago', tags: ['social_energy', 'active_lifestyle'] },
  { id: 'int_09', icon: '🎨', label: 'Painting & galleries', description: 'Tries to see one new exhibition a month', tags: ['creative_arts', 'intellectual_curiosity'] },
  { id: 'int_10', icon: '🧗', label: 'Bouldering', description: 'V4 climber, prefers indoor walls', tags: ['active_lifestyle', 'adventure'] },
  { id: 'int_11', icon: '🎬', label: 'Arthouse cinema', description: 'Letterboxd four-star average', tags: ['creative_arts', 'intellectual_curiosity'] },
  { id: 'int_12', icon: '🤝', label: 'Volunteering', description: 'Spends Saturday mornings at the food bank', tags: ['mindful_service', 'social_energy'] },
];

// Look calibration deck: each card is re-tagged with concrete physical-trait
// tokens and its photoUrl is generated by makeLabeledLookPhoto so the image
// always displays the card's own tags. All 14 appearance tags appear at least
// once across the deck, covering hair color, skin tone, build, and style axes.
export const LOOK_CALIBRATION_DECK: LookCalibrationCard[] = [
  { id: 'look_01', name: 'Sophie', age: 27, tags: ['blonde', 'slim_build', 'light_skin'],           photoUrl: makeLabeledLookPhoto(['blonde', 'slim_build', 'light_skin']) },
  { id: 'look_02', name: 'Hannah', age: 30, tags: ['dark_hair', 'athletic_build', 'medium_skin'],   photoUrl: makeLabeledLookPhoto(['dark_hair', 'athletic_build', 'medium_skin']) },
  { id: 'look_03', name: 'Aria',   age: 26, tags: ['red_hair', 'curvy_build', 'light_skin'],        photoUrl: makeLabeledLookPhoto(['red_hair', 'curvy_build', 'light_skin']) },
  { id: 'look_04', name: 'Naomi',  age: 32, tags: ['dark_skin', 'slim_build', 'clean_cut'],         photoUrl: makeLabeledLookPhoto(['dark_skin', 'slim_build', 'clean_cut']) },
  { id: 'look_05', name: 'Iris',   age: 29, tags: ['light_brown_hair', 'athletic_build', 'medium_skin'], photoUrl: makeLabeledLookPhoto(['light_brown_hair', 'athletic_build', 'medium_skin']) },
  { id: 'look_06', name: 'Ben',    age: 28, tags: ['blonde', 'full_build', 'light_skin'],           photoUrl: makeLabeledLookPhoto(['blonde', 'full_build', 'light_skin']) },
  { id: 'look_07', name: 'Daniel', age: 31, tags: ['dark_hair', 'tall', 'clean_cut'],               photoUrl: makeLabeledLookPhoto(['dark_hair', 'tall', 'clean_cut']) },
  { id: 'look_08', name: 'Marco',  age: 29, tags: ['dark_skin', 'athletic_build', 'edgy_look'],     photoUrl: makeLabeledLookPhoto(['dark_skin', 'athletic_build', 'edgy_look']) },
  { id: 'look_09', name: 'Tom',    age: 27, tags: ['light_brown_hair', 'short', 'medium_skin'],     photoUrl: makeLabeledLookPhoto(['light_brown_hair', 'short', 'medium_skin']) },
  { id: 'look_10', name: 'Alex',   age: 33, tags: ['red_hair', 'slim_build', 'edgy_look'],          photoUrl: makeLabeledLookPhoto(['red_hair', 'slim_build', 'edgy_look']) },
];

export const CARD_TAGS_BY_ID: Record<string, CalibrationTag[]> = {
  ...Object.fromEntries(INTEREST_CALIBRATION_DECK.map((c) => [c.id, c.tags])),
  ...Object.fromEntries(LOOK_CALIBRATION_DECK.map((c) => [c.id, c.tags])),
};
